@extends('layouts.procurement')
@section('title','Dashboard thu mua')
@section('subtitle','Trại sắp có hàng, thu mua hôm nay và chuyển nhập kho')
@push('styles')<style>.farm-card{cursor:pointer;border:2px solid transparent;transition:.15s}.farm-card.selected{border-color:#16a34a;background:#f0fdf4;box-shadow:0 0 0 3px #16a34a22}.money{font-weight:800;color:#b91c1c}</style>@endpush
@section('content')
<div class="row g-3 mb-4">
 <div class="col-lg-7"><div class="card border-0 shadow-sm"><div class="card-header bg-white"><strong>Trại có hàng / sắp có hàng trong 7 ngày</strong><div class="small text-muted">Dựa trên lần bắt gần nhất + 39–45 ngày. Chọn một trại để thu mua hôm nay.</div></div><div class="card-body"><div class="row g-2">
 @forelse($farms as $farm)<div class="col-md-6"><div class="farm-card card h-100 p-3" data-farm-id="{{ $farm->id }}" data-farm-name="{{ $farm->name }}"><div class="d-flex justify-content-between"><strong>{{ $farm->name }}</strong><span class="badge {{ $farm->availability==='overdue'?'bg-danger':($farm->availability==='soon'?'bg-success':'bg-secondary') }}">{{ $farm->availability==='overdue'?'Đã tới kỳ':($farm->availability==='soon'?'Sắp có hàng':'Chưa có lịch sử') }}</span></div><div class="small text-muted mt-2"><i class="bi bi-geo-alt"></i> {{ $farm->address ?: 'Chưa có địa chỉ' }}</div><div class="small">{{ $farm->phone ?: '—' }} · Quy mô {{ number_format($farm->scale ?? 0) }} con · {{ $farm->duck_breed ?: 'Chưa rõ giống' }}</div><div class="small text-success mt-1">Dự kiến: {{ $farm->available_from?->format('d/m/Y') ?? '—' }} – {{ $farm->available_to?->format('d/m/Y') ?? '—' }}</div><button type="button" class="btn btn-sm btn-outline-success mt-2 js-select-farm">Chọn trại này</button></div></div>
 @empty <div class="text-muted">Chưa có trang trại phù hợp. Hãy thêm tại Danh sách trang trại.</div>@endforelse
 </div></div></div></div>
 <div class="col-lg-5"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-white"><strong>Thống kê hôm nay</strong></div><div class="card-body row text-center g-3"><div class="col-6"><div class="fs-2 fw-bold">{{ $todayPurchases->count() }}</div><small>lần thu mua</small></div><div class="col-6"><div class="fs-2 fw-bold">{{ number_format($todayPurchases->sum('quantity')) }}</div><small>con vịt</small></div><div class="col-6"><div class="fs-4 fw-bold">{{ number_format($todayPurchases->sum('total_weight'),1) }}</div><small>kg</small></div><div class="col-6"><div class="fs-4 money">{{ number_format($todayPurchases->sum('total_amount')) }}đ</div><small>tổng chi</small></div></div></div></div>
</div>

<div class="card border-0 shadow-sm mb-4" id="purchaseFormCard"><div class="card-header bg-white"><strong>Form thu mua</strong><span id="selectedFarmLabel" class="badge bg-success ms-2 d-none"></span></div><div class="card-body">
<form method="POST" action="{{ route('procurement.purchases.store') }}" id="purchaseForm">@csrf
<div class="row g-3"><div class="col-md-3"><label class="form-label">Hình thức mua</label><select class="form-select" name="purchase_type" id="purchaseType"><option value="live_duck">Vịt lông tại trại</option><option value="processed_duck">Vịt thịt đã sơ chế</option></select></div>
<div class="col-md-3 live-field"><label class="form-label">Trang trại</label><select class="form-select" name="duck_farm_id" id="farmSelect"><option value="">Chọn trại</option>@foreach($farms as $farm)<option value="{{ $farm->id }}">{{ $farm->name }}</option>@endforeach</select></div>
<div class="col-md-3 processed-field d-none"><label class="form-label">Nhà cung cấp</label><select class="form-select" name="supplier_id"><option value="">Chọn NCC</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Loại/giống vịt</label><input class="form-control" name="duck_type" placeholder="Vịt bầu, vịt siêu thịt..."></div><div class="col-md-3"><label class="form-label">Ngày giờ bắt/mua</label><input type="datetime-local" class="form-control" name="purchased_at" value="{{ now()->format('Y-m-d\TH:i') }}" required></div>
<div class="col-md-2"><label class="form-label">Số lượng con</label><input type="number" min="1" class="form-control calc" name="quantity" id="quantity" required></div><div class="col-md-2"><label class="form-label">Tổng kg</label><input type="number" min="0" step=".001" class="form-control calc" name="total_weight" id="weight" required></div><div class="col-md-2 live-field"><label class="form-label">Size vịt lông</label><select class="form-select" name="live_size">@foreach($liveSizes as $size)<option value="{{ $size }}">{{ number_format($size,1) }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Giá mua/kg</label><input type="number" min="0" class="form-control calc" name="unit_price" id="price" required></div><div class="col-md-2"><label class="form-label">Phí cò</label><input type="number" min="0" value="0" class="form-control calc" name="broker_fee" id="brokerFee"></div><div class="col-md-2 live-field"><label class="form-label">Phí sơ chế</label><input type="number" min="0" value="0" class="form-control calc" name="processing_fee" id="processingFee"></div>
<div class="col-md-3"><label class="form-label">Thanh toán</label><select class="form-select" name="payment_status"><option value="unpaid">Chưa thanh toán</option><option value="partial">Thanh toán một phần</option><option value="paid">Đã thanh toán</option></select></div><div class="col-md-3"><label class="form-label">Tình trạng vịt</label><input class="form-control" name="duck_condition" placeholder="Khỏe, gầy, lỗi..."></div><div class="col-md-6"><label class="form-label">Ghi chú</label><input class="form-control" name="notes"></div>
</div>
<div class="processed-field d-none mt-3"><label class="fw-semibold mb-2">Phân loại size vịt thịt</label><div class="row g-2">@foreach($processedSizes as $size)<div class="col-4 col-md-2"><label class="small">Size {{ number_format($size,1) }}</label><input type="number" min="0" value="0" class="form-control form-control-sm" name="sizes[{{ $size }}]"></div>@endforeach</div></div>
<div class="alert alert-light border mt-3 d-flex flex-wrap gap-4"><span>Size TB: <strong id="avgPreview">0</strong> kg/con</span><span>Tiền hàng: <strong id="subtotalPreview">0đ</strong></span><span>Tổng chi: <strong class="money" id="totalPreview">0đ</strong></span></div><button class="btn btn-primary"><i class="bi bi-check2-circle me-1"></i>Ghi nhận thu mua</button>
</form></div></div>

<div class="card border-0 shadow-sm"><div class="card-header bg-white"><strong>Nhật ký thu mua hôm nay</strong></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Mã</th><th>Nguồn mua</th><th>Loại</th><th>SL/Kg/Size TB</th><th>Thành tiền</th><th>Thanh toán</th><th>Trạng thái</th><th>Gửi nhập kho</th></tr></thead><tbody>@forelse($todayPurchases as $p)<tr><td class="fw-bold">{{ $p->code }}</td><td>{{ $p->farm?->name ?? $p->supplier?->name }}</td><td>{{ $p->purchase_type==='live_duck'?'Vịt lông':'Vịt thịt' }}</td><td>{{ number_format($p->quantity) }} con / {{ number_format($p->total_weight,1) }}kg / {{ number_format($p->average_weight,2) }}</td><td>{{ number_format($p->total_amount) }}đ</td><td>{{ $p->payment_status }}</td><td><span class="badge bg-secondary">{{ $p->status }}</span></td><td>@if($p->status==='draft')<form class="d-flex gap-1" method="POST" action="{{ route('procurement.purchases.send-warehouse',$p) }}">@csrf<select class="form-select form-select-sm" name="warehouse_id" required><option value="">Chọn kho</option>@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->name }}</option>@endforeach</select><button class="btn btn-sm btn-success">Gửi</button></form>@else {{ $p->warehouse?->name ?? '—' }} @endif</td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">Chưa có lần thu mua hôm nay.</td></tr>@endforelse</tbody></table></div></div>
@endsection
@push('scripts')<script>
const type=document.getElementById('purchaseType');function syncType(){const live=type.value==='live_duck';document.querySelectorAll('.live-field').forEach(e=>e.classList.toggle('d-none',!live));document.querySelectorAll('.processed-field').forEach(e=>e.classList.toggle('d-none',live))}type.addEventListener('change',syncType);syncType();
document.querySelectorAll('.farm-card').forEach(card=>{card.addEventListener('click',()=>{document.querySelectorAll('.farm-card').forEach(c=>c.classList.remove('selected'));card.classList.add('selected');document.getElementById('farmSelect').value=card.dataset.farmId;type.value='live_duck';syncType();const b=document.getElementById('selectedFarmLabel');b.textContent='Đã chọn: '+card.dataset.farmName;b.classList.remove('d-none');document.getElementById('purchaseFormCard').scrollIntoView({behavior:'smooth'})})});
function calc(){const q=+document.getElementById('quantity').value||0,w=+document.getElementById('weight').value||0,p=+document.getElementById('price').value||0,b=+document.getElementById('brokerFee').value||0,s=+document.getElementById('processingFee').value||0;document.getElementById('avgPreview').textContent=q?(w/q).toFixed(2):'0';document.getElementById('subtotalPreview').textContent=(w*p).toLocaleString('vi-VN')+'đ';document.getElementById('totalPreview').textContent=(w*p+b+s).toLocaleString('vi-VN')+'đ'}document.querySelectorAll('.calc').forEach(e=>e.addEventListener('input',calc));
</script>@endpush
