<?php

return [
    'catalog' => [
        'website_admin' => [
            'label' => 'Website / Admin',
            'description' => 'Dashboard quan tri tong hop.',
            'platform' => 'website',
            'route' => 'dashboard',
            'role_hints' => ['admin', 'factory'],
        ],
        'website_ceo' => [
            'label' => 'Website / CEO',
            'description' => 'Dashboard dieu hanh CEO.',
            'platform' => 'website',
            'route' => 'ceo.dashboard',
            'role_hints' => ['ceo'],
        ],
        'website_accounting' => [
            'label' => 'Website / Accounting',
            'description' => 'Dashboard ke toan.',
            'platform' => 'website',
            'route' => 'accounting.dashboard',
            'role_hints' => ['accountant', 'accounting'],
        ],
        'website_warehouse' => [
            'label' => 'Website / Warehouse',
            'description' => 'Dashboard kho.',
            'platform' => 'website',
            'route' => 'warehouse.dashboard',
            'role_hints' => ['warehouse'],
        ],
        'website_package' => [
            'label' => 'Website / Package',
            'description' => 'Dashboard dong hang.',
            'platform' => 'website',
            'route' => 'package.dashboard',
            'role_hints' => ['package'],
        ],
        'website_shipper' => [
            'label' => 'Website / Shipper',
            'description' => 'Dashboard shipper va dieu phoi ship.',
            'platform' => 'website',
            'route' => 'shipper.dashboard',
            'role_hints' => ['shipper', 'ship', 'manager_shipper'],
        ],
        'website_sales' => [
            'label' => 'Website / Sales',
            'description' => 'Dashboard kinh doanh.',
            'platform' => 'website',
            'route' => 'pages.my_dashboard',
            'role_hints' => ['sale', 'leader', 'leader_sale', 'sale_manager', 'manager', 'manager_sale'],
        ],
        'my_app_home' => [
            'label' => 'My_app / Home',
            'description' => 'Dieu huong my_app theo role mobile.',
            'platform' => 'my_app',
            'route' => 'mobile.home',
            'role_hints' => ['admin', 'factory'],
            'mobile_layout' => 'home',
        ],
        'my_app_package' => [
            'label' => 'My_app / Package',
            'description' => 'Giao dien my_app cho bo phan dong hang.',
            'platform' => 'my_app',
            'route' => 'mobile.home',
            'role_hints' => ['package'],
            'mobile_layout' => 'package',
        ],
        'my_app_accounting' => [
            'label' => 'My_app / Accounting',
            'description' => 'Giao dien my_app cho ke toan.',
            'platform' => 'my_app',
            'route' => 'mobile.home',
            'role_hints' => ['accountant', 'accounting'],
            'mobile_layout' => 'accounting',
        ],
        'my_app_ceo' => [
            'label' => 'My_app / CEO',
            'description' => 'Giao dien my_app cho CEO.',
            'platform' => 'my_app',
            'route' => 'mobile.home',
            'role_hints' => ['ceo'],
            'mobile_layout' => 'ceo',
        ],
        'my_app_warehouse' => [
            'label' => 'My_app / Warehouse',
            'description' => 'Giao dien my_app cho kho.',
            'platform' => 'my_app',
            'route' => 'mobile.warehouse.home',
            'role_hints' => ['warehouse', 'admin'],
            'mobile_layout' => 'warehouse',
        ],
        'my_app_shipper' => [
            'label' => 'My_app / Shipper',
            'description' => 'Giao dien my_app cho shipper.',
            'platform' => 'my_app',
            'route' => 'mobile.shipper.home',
            'role_hints' => ['shipper', 'ship', 'admin'],
            'mobile_layout' => 'shipper',
        ],
        'my_app_manager_shipper' => [
            'label' => 'My_app / Manager Shipper',
            'description' => 'Giao dien my_app cho dieu phoi ship.',
            'platform' => 'my_app',
            'route' => 'mobile.shipper.home',
            'role_hints' => ['manager_shipper'],
            'mobile_layout' => 'manager_shipper',
        ],
        'my_app_sales' => [
            'label' => 'My_app / Sales',
            'description' => 'Giao dien my_app cho sales.',
            'platform' => 'my_app',
            'route' => 'mobile.sale.home',
            'role_hints' => ['sale', 'leader', 'leader_sale', 'sale_manager', 'manager', 'manager_sale', 'admin'],
            'mobile_layout' => 'sale',
        ],
    ],
];
