<!doctype html>
<html lang="vi"><head><meta charset="utf-8"><title>Phiếu xuất kho tổng {{ $slip->code }}</title>
<style>
@page{size:A4 portrait;margin:10mm}*{box-sizing:border-box}html,body{min-height:100%}body{font-family:"DejaVu Sans",Arial,sans-serif;color:#111;font-size:10.5px;margin:0;padding:24px;background:#e5e7eb}.print-sheet{width:210mm;max-width:100%;min-height:297mm;margin:0 auto;padding:12mm;background:#fff;box-shadow:0 4px 24px rgba(15,23,42,.16)}.no-print{position:fixed;right:24px;top:18px;z-index:10;border:0;border-radius:7px;background:#0f766e;color:#fff;font-weight:700;padding:9px 16px;cursor:pointer;box-shadow:0 2px 8px rgba(15,23,42,.2)}h1{font-size:20px;text-align:center;margin:3px 0}h3{font-size:12px;margin:12px 0 5px;break-after:avoid}.sub{text-align:center;margin-bottom:12px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:5px 22px;margin:12px 0;padding:8px;border:1px solid #cbd5e1;background:#f8fafc}.meta>div{min-width:0;overflow-wrap:anywhere}.box{border:1px solid #222;padding:8px;margin:8px 0}.handover-note{min-height:70px;white-space:pre-wrap;overflow-wrap:anywhere}.order-note{font-size:9px;white-space:pre-wrap;overflow-wrap:anywhere}table{width:100%;max-width:100%;table-layout:fixed;border-collapse:collapse;margin:6px 0 10px}thead{display:table-header-group}tr{break-inside:avoid}th,td{border:1px solid #333;padding:4px 5px;vertical-align:top;overflow-wrap:anywhere}th{background:#eee;text-align:left;font-size:9.5px}.num{text-align:right;white-space:nowrap}.center{text-align:center}.order-table th:nth-child(1){width:5%}.order-table th:nth-child(2){width:13%}.order-table th:nth-child(3){width:16%}.order-table th:nth-child(4){width:12%}.order-table th:nth-child(5){width:11%}.order-table th:nth-child(6){width:13%}.order-table th:nth-child(7){width:30%}.transfer-table th:nth-child(1){width:5%}.transfer-table th:nth-child(2){width:19%}.transfer-table th:nth-child(3){width:12%}.transfer-table th:nth-child(4){width:13%}.transfer-table th:nth-child(5){width:15%}.transfer-table th:nth-child(6){width:36%}.summary-table th:nth-child(1){width:6%}.summary-table th:nth-child(2){width:34%}.summary-table th:nth-child(3){width:16%}.summary-table th:nth-child(4){width:12%}.summary-table th:nth-child(5){width:14%}.summary-table th:nth-child(6){width:18%}.sign{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;text-align:center;margin-top:22px;break-inside:avoid}.sign-space{height:58px}.draft{color:#b91c1c;text-align:center;font-size:13px;font-weight:bold}.small{font-size:9px;color:#444}@media(max-width:850px){body{padding:12px}.no-print{position:static;display:block;margin:0 auto 12px}.print-sheet{min-height:auto;padding:8mm}}@media print{html,body{min-height:auto}body{padding:0;background:#fff}.no-print{display:none}.print-sheet{width:auto;max-width:none;min-height:auto;margin:0;padding:0;box-shadow:none}}
</style></head><body>
@php($formatKg = static fn (float|int|string $value): string => rtrim(rtrim(number_format((float) $value, 3, ',', '.'), '0'), ',').' kg')
<button class="no-print" onclick="window.print()">In phiếu</button>
<main class="print-sheet">
<div class="small">HOÀNG LONG TNT</div><h1>PHIẾU XUẤT KHO TỔNG</h1><div class="sub"><strong>{{ $slip->code }}</strong> · Ngày {{ $slip->business_date->format('d/m/Y') }}</div>
@if($slip->status === 'draft')<div class="draft">BẢN NHÁP — PHIẾU CHƯA CHỐT</div>@endif
<div class="meta"><div>Kho xuất: <strong>{{ $slip->sourceWarehouse?->name }}</strong></div><div>Kho nhận: <strong>{{ $slip->targetWarehouse?->name }}</strong></div><div>Địa chỉ xuất: {{ $slip->sourceWarehouse?->address ?: '—' }}</div><div>Địa chỉ nhận: {{ $slip->targetWarehouse?->address ?: '—' }}</div><div>Tài xế: <strong>{{ $slip->shipper?->name }}</strong></div><div>Điện thoại: {{ $slip->shipper?->phone ?: '—' }}</div><div>Người lập: {{ $slip->creator?->name }}</div><div>Chốt lúc: {{ optional($slip->finalized_at)->format('d/m/Y H:i') ?: 'Chưa chốt' }}</div></div>

<h3>A. DANH SÁCH ĐƠN HOÀN THIỆN</h3>
<table class="order-table"><thead><tr><th class="center">STT</th><th>Mã đơn</th><th>Khách hàng</th><th>Sale</th><th class="num">SL dòng hàng</th><th class="num">KL bàn giao</th><th>Ghi chú đơn</th></tr></thead><tbody>
@forelse($orderRows as $row)<tr><td class="center">{{ $loop->iteration }}</td><td>{{ $row['code'] }}</td><td>{{ $row['customer_name'] }}</td><td>{{ $row['sale_name'] }}</td><td class="num">{{ number_format($row['item_quantity']) }}</td><td class="num">{{ $formatKg($row['packed_weight']) }}</td><td class="order-note">{{ filled($row['order_note']) ? $row['order_note'] : '—' }}</td></tr>@empty<tr><td colspan="7" class="center">Không có đơn hoàn thiện.</td></tr>@endforelse
</tbody></table>

<h3>B. PHIẾU ĐIỀU CHUYỂN HÀNG</h3>
<table class="transfer-table"><thead><tr><th class="center">STT</th><th>Mã phiếu điều chuyển</th><th class="num">Số mặt hàng</th><th class="num">Tổng số lượng</th><th class="num">Tổng khối lượng</th><th>Ghi chú điều chuyển</th></tr></thead><tbody>
@forelse($inventoryTransferRows as $row)<tr><td class="center">{{ $loop->iteration }}</td><td><strong>{{ $row['code'] }}</strong></td><td class="num">{{ number_format($row['item_count']) }}</td><td class="num">{{ number_format($row['quantity']) }}</td><td class="num">{{ $formatKg($row['weight']) }}</td><td class="order-note">{{ filled($row['note']) ? $row['note'] : '—' }}</td></tr>@empty<tr><td colspan="6" class="center">Phiếu không có hàng điều chuyển.</td></tr>@endforelse
</tbody></table>

<h3>C. BẢNG TỔNG HỢP HÀNG HÓA</h3>
<table class="summary-table"><thead><tr><th class="center">STT</th><th>Sản phẩm</th><th>SKU</th><th>Size</th><th class="num">Số lượng</th><th class="num">Khối lượng</th></tr></thead><tbody>
@foreach($summaryRows as $row)<tr><td class="center">{{ $loop->iteration }}</td><td>{{ $row['product_name'] }}</td><td>{{ $row['sku'] ?: '—' }}</td><td>{{ $row['size'] ?: '—' }}</td><td class="num">{{ number_format($row['quantity']) }}</td><td class="num">{{ $formatKg($row['weight']) }}</td></tr>@endforeach
</tbody><tfoot><tr><th colspan="4">Tổng cộng</th><th class="num">{{ number_format($summaryRows->sum('quantity')) }}</th><th class="num">{{ $formatKg($summaryRows->sum('weight')) }}</th></tr></tfoot></table>

<h3>D. GHI CHÚ BÀN GIAO</h3>
<div class="box handover-note">{{ filled($slip->notes) ? $slip->notes : "........................................................................................................................................\n........................................................................................................................................" }}</div>
<div class="sign"><div><strong>NGƯỜI LẬP PHIẾU</strong><div class="small">(Ký, ghi rõ họ tên)</div><div class="sign-space"></div>{{ $slip->creator?->name }}</div><div><strong>THỦ KHO XUẤT</strong><div class="small">(Ký, ghi rõ họ tên)</div><div class="sign-space"></div></div><div><strong>TÀI XẾ NHẬN HÀNG</strong><div class="small">(Ký, ghi rõ họ tên)</div><div class="sign-space"></div>{{ $slip->shipper?->name }}</div></div>
</main>
</body></html>
