@extends($layout)
@section('title','Quản lý chi phí ship')
@include('processes.styles')
@section('content')
<div class="container-fluid process-page"><div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div><h1>{{ $queue==='coordination'?'Điều phối xác nhận chi phí ship':($queue==='accounting'?'Kế toán xác nhận chi phí ship':'Quản lý phí ship của tôi') }}</h1><div class="text-muted">Theo dõi yêu cầu, điều chỉnh, số liệu đã chốt và thanh toán.</div></div>@if(app(\App\Services\ProcessEngine::class)->hasRole(auth()->user(),'shipper'))<a class="btn btn-primary align-self-start" href="{{ route('shipping-expenses.create') }}">+ Ghi nhận phí ship</a>@endif</div>
@include('processes.shipping-tabs', ['activeTab' => 'requests'])
@include('processes.messages')
<form class="process-card row g-2"><input type="hidden" name="tab" value="requests"><input type="hidden" name="queue" value="{{ $queue }}"><div class="col-md-5"><input class="form-control" name="q" value="{{ request('q') }}" placeholder="Tìm Shipper"></div><div class="col-md-4"><select class="form-select" name="status"><option value="">Tất cả trạng thái</option>@foreach(['running'=>'Chờ xử lý','revision'=>'Yêu cầu điều chỉnh','confirmed'=>'Đã chốt','rejected'=>'Đã từ chối'] as $key=>$label)<option value="{{ $key }}" @selected(request('status')===$key)>{{ $label }}</option>@endforeach</select></div><div class="col-md-3"><button class="btn btn-primary">Lọc</button></div></form>
<div class="process-card table-responsive"><table class="process-table"><thead><tr><th>STT</th><th>Yêu cầu</th><th>Shipper</th><th>Tổng phí</th><th>Trạng thái</th><th>Tiến trình xử lý</th><th>Thanh toán</th><th>Thao tác</th></tr></thead><tbody>@forelse($claims as $claim)<tr><td>{{ $claims->firstItem()+$loop->index }}</td><td>#{{ $claim->id }}<div class="small text-muted">{{ $claim->created_at->format('d/m/Y H:i') }}</div></td><td>{{ $claim->shipper?->name }}</td><td>{{ number_format($claim->total,0,',','.') }}đ</td><td><span class="process-status">{{ $claim->run->statusLabel() }}</span></td><td class="text-nowrap">@if($claim->run->status === 'revision')<strong>Cần điều chỉnh</strong> &amp; Gửi lại
@else
{{ $claim->run->statusLabel() }}@endif</td><td>{{ $claim->payment_transaction_id?'Đã gửi phiếu #'.$claim->payment_transaction_id:'Chưa gửi' }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('shipping-expenses.show',$claim) }}">Xem / xử lý</a></td></tr>@empty<tr><td colspan="8" class="text-center text-muted">Chưa có yêu cầu.</td></tr>@endforelse</tbody></table>{{ $claims->links() }}</div></div>
@endsection
