@extends('layouts.warehouse')
@section('title', 'Báo cáo kho')
@section('content')
<style>
.report-hero{background:linear-gradient(135deg,#0f766e,#164e63);color:#fff;border-radius:16px;padding:24px;margin-bottom:20px}.report-hero h1{font-size:1.65rem;font-weight:750;margin:0 0 4px}.report-panel,.metric{background:#fff;border:1px solid #e8edf2;border-radius:14px;box-shadow:0 2px 10px rgba(15,23,42,.04)}.report-panel{margin-bottom:20px;overflow:hidden}.report-title{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:16px 18px;border-bottom:1px solid #e8edf2}.report-title h2{font-size:1.05rem;font-weight:750;margin:0}.metric{padding:16px;height:100%}.metric .value{color:#0f766e;font-size:1.55rem;line-height:1.15;font-weight:800}.metric .label{color:#64748b;font-size:.82rem;margin-top:6px}.report-table{margin:0;min-width:900px}.report-table th{background:#f8fafc;color:#475569;font-size:.76rem;text-transform:uppercase;white-space:nowrap}.report-table td,.report-table th{padding:11px 14px;vertical-align:middle;border-color:#edf1f5}.product-cell strong{display:block}.product-cell small{color:#64748b}.empty-state{color:#64748b;text-align:center;padding:34px 16px!important}.sub-row{background:#fbfdff}.money{white-space:nowrap;font-variant-numeric:tabular-nums}.section-anchor{scroll-margin-top:85px}
</style>
<div class="report-hero"><h1><i class="bi bi-clipboard-data me-2"></i>Báo cáo kho</h1><div class="opacity-75">Nhập nhà cung cấp, hàng điều chuyển, đơn đã xuất và tồn kho</div></div>
<div class="report-panel p-3"><form method="GET" class="row g-3 align-items-end">
<div class="col-md-3"><label class="form-label fw-semibold">Kỳ báo cáo</label><select name="range_type" class="form-select" id="rangeType"><option value="day" @selected($rangeType==='day')>Theo ngày</option><option value="week" @selected($rangeType==='week')>Theo tuần</option><option value="month" @selected($rangeType==='month')>Theo tháng</option><option value="year" @selected($rangeType==='year')>Theo năm</option><option value="custom" @selected($rangeType==='custom')>Tùy chỉnh</option></select></div>
<div class="col-md-3"><label class="form-label fw-semibold">Ngày bắt đầu / ngày đại diện</label><input type="date" name="selected_date" class="form-control" value="{{ $selectedDate }}"></div>
<div class="col-md-3" id="endDateWrap" @if($rangeType!=='custom') style="display:none" @endif><label class="form-label fw-semibold">Đến ngày</label><input type="date" name="end_date" class="form-control" value="{{ $endDate }}"></div>
<div class="col-md-3 d-flex gap-2"><button class="btn btn-primary flex-grow-1"><i class="bi bi-funnel me-1"></i>Xem báo cáo</button><a href="{{ route('warehouse.reports') }}" class="btn btn-outline-secondary" title="Hôm nay"><i class="bi bi-arrow-clockwise"></i></a></div>
</form></div>
<div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div><strong>Kỳ báo cáo:</strong> {{ $from->format('d/m/Y') }} – {{ $to->format('d/m/Y') }}</div><div class="d-flex flex-wrap gap-2"><a href="#supplier-imports" class="btn btn-sm btn-outline-primary">Nhập NCC</a><a href="#transfers" class="btn btn-sm btn-outline-primary">Điều chuyển</a><a href="#exported-orders" class="btn btn-sm btn-outline-primary">Đơn đã xuất</a><a href="#inventory" class="btn btn-sm btn-outline-primary">Tồn kho</a></div></div>
<div class="row g-3 mb-4">
<div class="col-6 col-xl"><div class="metric"><div class="value">{{ number_format($totals['supplier_quantity'],0,',','.') }}</div><div class="label">SL nhập từ NCC</div></div></div><div class="col-6 col-xl"><div class="metric"><div class="value money">{{ number_format($totals['supplier_amount'],0,',','.') }} ₫</div><div class="label">Tổng tiền nhập</div></div></div><div class="col-6 col-xl"><div class="metric"><div class="value">{{ number_format($totals['transfer_quantity'],0,',','.') }}</div><div class="label">SL nhập điều chuyển</div></div></div><div class="col-6 col-xl"><div class="metric"><div class="value">{{ number_format($totals['exported_orders'],0,',','.') }}</div><div class="label">Đơn đã xuất</div></div></div><div class="col-6 col-xl"><div class="metric"><div class="value">{{ number_format($totals['on_hand'],0,',','.') }}</div><div class="label">Tồn thực tế</div></div></div>
</div>
<section class="report-panel section-anchor" id="supplier-imports"><div class="report-title"><h2><i class="bi bi-truck me-2 text-primary"></i>1. Nhập hàng từ nhà cung cấp</h2><span class="badge bg-primary">{{ $supplierImports->count() }} phiếu</span></div><div class="table-responsive"><table class="table report-table"><thead><tr><th>Ngày / Phiếu</th><th>Nhà cung cấp</th><th>Sản phẩm</th><th>Size</th><th class="text-end">Số lượng</th><th class="text-end">Đơn giá</th><th class="text-end">Thành tiền</th></tr></thead><tbody>
@forelse($supplierImports as $document) @foreach($document->items as $item)<tr><td>@if($loop->first)<strong>{{ $document->document_date?->format('d/m/Y') }}</strong><small class="d-block text-muted">{{ $document->document_number?:'#'.$document->id }}</small>@endif</td><td>@if($loop->first){{ $document->supplier?->name??'Không xác định' }}@endif</td><td class="product-cell"><strong>{{ $item->productVariant?->product?->name??'Sản phẩm đã xóa' }}</strong><small>{{ $item->productVariant?->sku }}</small></td><td>{{ $item->productVariant?->size?:($item->productVariant?->name??'—') }}</td><td class="text-end">{{ number_format($item->quantity,0,',','.') }} {{ $item->productVariant?->product?->unit_label??'' }}</td><td class="text-end money">{{ number_format($item->unit_cost,0,',','.') }} ₫</td><td class="text-end money fw-semibold">{{ number_format($item->quantity*$item->unit_cost,0,',','.') }} ₫</td></tr>@endforeach
<tr class="sub-row"><td colspan="6" class="text-end fw-semibold">Tổng phiếu @if((float)$document->shipping_fee>0)<small class="text-muted">(gồm vận chuyển {{ number_format($document->shipping_fee,0,',','.') }} ₫)</small>@endif</td><td class="text-end money fw-bold">{{ number_format($document->items->sum(fn($i)=>$i->quantity*$i->unit_cost)+(float)$document->shipping_fee,0,',','.') }} ₫</td></tr>
@empty<tr><td colspan="7" class="empty-state">Không có phiếu nhập từ nhà cung cấp trong kỳ.</td></tr>@endforelse</tbody></table></div></section>
<section class="report-panel section-anchor" id="transfers"><div class="report-title"><h2><i class="bi bi-arrow-left-right me-2 text-info"></i>2. Nhập kho từ điều chuyển</h2><span class="badge bg-info text-dark">{{ $inventoryTransfers->count()+$orderTransfers->count() }} lượt nhận</span></div><div class="table-responsive"><table class="table report-table"><thead><tr><th>Loại / Mã</th><th>Ngày nhận</th><th>Kho gửi</th><th>Đơn hàng</th><th>Danh sách hàng</th><th class="text-end">Tổng SL</th></tr></thead><tbody>
@foreach($inventoryTransfers as $transfer)<tr><td><span class="badge bg-info text-dark">Điều chuyển hàng</span><small class="d-block mt-1">{{ $transfer->transfer_code }}</small></td><td>{{ $transfer->received_at?->format('d/m/Y H:i') }}</td><td>{{ $transfer->sourceWarehouse?->name??'—' }}</td><td>{{ $transfer->order?->code?'#'.$transfer->order->code:'—' }}</td><td>@foreach($transfer->items as $item)<div>{{ $item->variant?->product?->name }} — {{ $item->variant?->size?:$item->variant?->name }}: <strong>{{ number_format($item->quantity,0,',','.') }}</strong></div>@endforeach</td><td class="text-end fw-bold">{{ number_format($transfer->items->sum('quantity'),0,',','.') }}</td></tr>@endforeach
@foreach($orderTransfers as $transfer) @php($transferItems=$transfer->importDocument?->items??collect())<tr><td><span class="badge bg-warning text-dark">Điều chuyển đơn</span><small class="d-block mt-1">#{{ $transfer->id }}</small></td><td>{{ $transfer->received_at?->format('d/m/Y H:i') }}</td><td>{{ $transfer->sourceWarehouse?->name??'—' }}</td><td><strong>#{{ $transfer->order?->code??$transfer->order_id }}</strong><small class="d-block text-muted">{{ $transfer->order?->customer?->name }}</small></td><td>@forelse($transferItems as $item)<div>{{ $item->productVariant?->product?->name }} — {{ $item->productVariant?->size?:$item->productVariant?->name }}: <strong>{{ number_format($item->quantity,0,',','.') }}</strong></div>@empty @foreach($transfer->order?->items??[] as $item)<div>{{ $item->variant?->product?->name }}: <strong>{{ number_format($item->quantity,0,',','.') }}</strong></div>@endforeach @endforelse</td><td class="text-end fw-bold">{{ number_format($transferItems->isNotEmpty()?$transferItems->sum('quantity'):($transfer->order?->items->sum('quantity')??0),0,',','.') }}</td></tr>@endforeach
@if($inventoryTransfers->isEmpty()&&$orderTransfers->isEmpty())<tr><td colspan="6" class="empty-state">Không có hàng hoặc đơn điều chuyển được nhận trong kỳ.</td></tr>@endif</tbody></table></div></section>
<section class="report-panel section-anchor" id="exported-orders"><div class="report-title"><h2><i class="bi bi-box-arrow-up-right me-2 text-danger"></i>3. Danh sách đơn đã xuất</h2><span class="badge bg-danger">{{ $exportedOrders->count() }} đơn</span></div><div class="table-responsive"><table class="table report-table"><thead><tr><th>Ngày / Phiếu xuất</th><th>Mã đơn</th><th>Khách hàng</th><th>Shipper</th><th>Danh sách hàng</th><th class="text-end">Tổng SL</th></tr></thead><tbody>
@forelse($exportedOrders as $row)<tr><td>{{ $row['document']->document_date?->format('d/m/Y') }}<small class="d-block text-muted">{{ $row['document']->document_number?:'#'.$row['document']->id }}</small></td><td><strong>#{{ $row['order']->code }}</strong></td><td>{{ $row['order']->customer?->name??'—' }}</td><td>{{ $row['order']->shipper?->name??'—' }}</td><td>@foreach($row['document']->items as $item)<div>{{ $item->productVariant?->product?->name }} — {{ $item->productVariant?->size?:$item->productVariant?->name }}: <strong>{{ number_format($item->quantity,0,',','.') }}</strong></div>@endforeach</td><td class="text-end fw-bold">{{ number_format($row['document']->items->sum('quantity'),0,',','.') }}</td></tr>@empty<tr><td colspan="6" class="empty-state">Không có đơn đã xuất trong kỳ.</td></tr>@endforelse</tbody></table></div></section>
<section class="report-panel section-anchor" id="inventory"><div class="report-title"><h2><i class="bi bi-boxes me-2 text-success"></i>4. Tồn kho hiện tại</h2><div><span class="badge bg-success me-1">Tồn: {{ number_format($totals['on_hand'],0,',','.') }}</span><span class="badge bg-secondary">Khả dụng: {{ number_format($totals['available'],0,',','.') }}</span></div></div><div class="table-responsive"><table class="table report-table"><thead><tr><th>Kho</th><th>Sản phẩm</th><th>SKU</th><th>Size</th><th class="text-end">Tồn thực tế</th><th class="text-end">Đang giữ</th><th class="text-end">Khả dụng</th></tr></thead><tbody>
@forelse($inventory as $stock)<tr><td>{{ $stock->warehouse?->name??'—' }}</td><td><strong>{{ $stock->productVariant?->product?->name??'Sản phẩm đã xóa' }}</strong></td><td>{{ $stock->productVariant?->sku??'—' }}</td><td>{{ $stock->productVariant?->size?:($stock->productVariant?->name??'—') }}</td><td class="text-end fw-bold">{{ number_format($stock->quantity,0,',','.') }}</td><td class="text-end">{{ number_format($stock->reserved_quantity,0,',','.') }}</td><td class="text-end text-success fw-bold">{{ number_format(max(0,$stock->quantity-$stock->reserved_quantity),0,',','.') }}</td></tr>@empty<tr><td colspan="7" class="empty-state">Kho chưa có dữ liệu tồn.</td></tr>@endforelse</tbody></table></div></section>
<script>document.getElementById('rangeType')?.addEventListener('change',function(){document.getElementById('endDateWrap').style.display=this.value==='custom'?'':'none'});</script>
@endsection
