@extends('layouts.warehouse')
@section('title', 'Báo cáo kho theo ngày')
@section('content')
@php
    $number = fn ($value, $decimals = 0) => number_format((float) $value, $decimals, ',', '.');
    $size = fn ($variant) => $variant && (float) $variant->size > 0 ? rtrim(rtrim($number($variant->size, 3), '0'), ',') : '—';
    $variantWeight = fn ($variant, $quantity) => (float) $quantity * (float) ($variant?->effective_kg ?? 0);
    $supplierTotal = $supplierImports->sum(fn ($doc) => $doc->items->sum(fn ($item) => (float)$item->quantity * (float)$item->unit_cost) + (float)$doc->shipping_fee);
    $inventoryTransferTotal = $inventoryTransfers->sum(fn ($transfer) => $transfer->items->sum(fn ($item) => (float)$item->quantity * (float)$item->unit_cost));
    $orderTransferTotal = $orderTransfers->sum(fn ($transfer) => ($transfer->order?->items ?? collect())->sum(fn ($item) => $item->lineTotalForStage($transfer->order->status)));
    $outgoingTotal = $exportedOrders->sum(fn ($row) => $row['order'] ? $row['order']->items->sum(fn ($item) => $item->lineTotalForStage($row['order']->status)) : $row['document']->items->sum(fn ($item) => (float)$item->quantity * (float)$item->unit_cost));
@endphp
<style>
.daily-head{background:linear-gradient(135deg,#0f766e,#164e63);color:#fff;border-radius:15px;padding:20px;margin-bottom:16px}.daily-panel{background:#fff;border:1px solid #e5ebf1;border-radius:13px;box-shadow:0 2px 9px rgba(15,23,42,.04);overflow:hidden;margin-bottom:16px}.daily-title{display:flex;justify-content:space-between;align-items:center;padding:13px 15px;border-bottom:1px solid #e8edf2}.daily-title h2{font-size:1rem;font-weight:750;margin:0}.daily-table{margin:0}.daily-table th{background:#f8fafc;color:#475569;font-size:.72rem;text-transform:uppercase;white-space:nowrap}.daily-table td,.daily-table th{padding:9px 11px;vertical-align:middle;border-color:#edf1f5}.empty{text-align:center;color:#64748b;padding:25px!important}.total-row th{background:#dff4ec;color:#075e54;font-size:.86rem}.num{text-align:right;white-space:nowrap}.money{font-weight:700;color:#075e54}.report-note{font-size:.76rem;color:#64748b}
</style>
<div class="daily-head"><h1 class="h4 fw-bold mb-1">Báo cáo kho theo ngày — {{ $warehouse?->name ?? 'Toàn hệ thống' }}</h1><div class="opacity-75">{{ $from->format('d/m/Y') }}</div></div>
<div class="daily-panel p-3"><form method="GET" class="d-flex flex-wrap align-items-end gap-2"><div><label class="form-label fw-semibold">Ngày làm việc</label><input type="date" name="selected_date" class="form-control" value="{{ $selectedDate }}"></div><button class="btn btn-primary"><i class="bi bi-funnel me-1"></i>Xem</button></form></div>

<section class="daily-panel"><div class="daily-title"><h2>1. Tồn kho</h2><span class="badge bg-success">Tồn cuối: {{ $number($inventorySummary['totals']['closing']) }}</span></div><div class="table-responsive"><table class="table daily-table"><thead><tr><th>Sản phẩm</th><th>ĐVT</th><th>Size</th><th class="num">Tồn đầu</th><th class="num">Nhập</th><th class="num">Tổng</th><th class="num">Book</th><th class="num">Xuất</th><th class="num">Khả dụng</th><th class="num">Tồn cuối</th></tr></thead><tbody>
@php($inventoryRows=0)
@foreach($inventorySummary['rows'] as $product) @foreach($product['variants'] as $variant) @if($variant['opening']!=0||$variant['import']!=0||$variant['reserved']!=0||$variant['export']!=0||$variant['closing']!=0) @php($inventoryRows++)<tr><td>{{ $product['name'] }}</td><td>{{ $variant['unit'] }}</td><td>{{ (float)$variant['size']>0?rtrim(rtrim($number($variant['size'],3),'0'),','):'—' }}</td><td class="num">{{ $number($variant['opening']) }}</td><td class="num">{{ $number($variant['import']) }}</td><td class="num fw-semibold">{{ $number($variant['opening']+$variant['import']) }}</td><td class="num">{{ $number($variant['reserved']) }}</td><td class="num">{{ $number($variant['export']) }}</td><td class="num">{{ $number($variant['available']) }}</td><td class="num fw-bold">{{ $number($variant['closing']) }}</td></tr>@endif @endforeach @endforeach
@if($inventoryRows===0)<tr><td colspan="10" class="empty">Không có phát sinh hoặc tồn kho trong ngày.</td></tr>@endif
</tbody><tfoot><tr class="total-row"><th colspan="3">TỔNG CỘNG</th><th class="num">{{ $number($inventorySummary['totals']['opening']) }}</th><th class="num">{{ $number($inventorySummary['totals']['import']) }}</th><th class="num">{{ $number($inventorySummary['totals']['opening']+$inventorySummary['totals']['import']) }}</th><th class="num">{{ $number($inventorySummary['totals']['reserved']) }}</th><th class="num">{{ $number($inventorySummary['totals']['export']) }}</th><th class="num">{{ $number($inventorySummary['totals']['available']) }}</th><th class="num">{{ $number($inventorySummary['totals']['closing']) }}</th></tr></tfoot></table></div></section>

<section class="daily-panel"><div class="daily-title"><h2>2. Hàng Thu mua DT3</h2><span class="badge bg-primary">{{ $number($totals['supplier_quantity']) }} sản phẩm</span></div><div class="table-responsive"><table class="table daily-table"><thead><tr><th>Nhà cung cấp</th><th>Sản phẩm</th><th>ĐVT</th><th>Size</th><th class="num">Số lượng</th><th class="num">Khối lượng</th><th class="num">Giá</th><th class="num">Thành tiền</th></tr></thead><tbody>
@forelse($supplierImports as $document) @foreach($document->items as $item) @php($variant=$item->productVariant)<tr><td>{{ $document->supplier?->name??'—' }}</td><td>{{ $variant?->product?->name??'Sản phẩm' }}</td><td>{{ $variant?->product?->unit_label??'—' }}</td><td>{{ $size($variant) }}</td><td class="num">{{ $number($item->quantity) }}</td><td class="num">{{ $number($variantWeight($variant,$item->quantity),3) }} kg</td><td class="num">{{ $number($item->unit_cost) }}đ</td><td class="num money">{{ $number($item->quantity*$item->unit_cost) }}đ</td></tr>@endforeach @empty<tr><td colspan="8" class="empty">Không có hàng thu mua DT3.</td></tr>@endforelse
</tbody><tfoot><tr class="total-row"><th colspan="7">TỔNG TIỀN NHẬP</th><th class="num">{{ $number($supplierTotal) }}đ</th></tr></tfoot></table></div></section>

<section class="daily-panel"><div class="daily-title"><h2>3. Hàng &amp; đơn xuất đi</h2><span class="badge bg-danger">{{ $number($exportedOrders->sum(fn($row)=>$row['document']->items->sum('quantity'))) }} sản phẩm</span></div><div class="table-responsive"><table class="table daily-table"><thead><tr><th>Khách hàng</th><th>Sản phẩm</th><th>Size</th><th class="num">SL</th><th class="num">KL</th><th class="num">Giá</th><th class="num">Thành tiền</th></tr></thead><tbody>
@forelse($exportedOrders as $row) @foreach($row['document']->items as $item) @php($variant=$item->productVariant) @php($orderItem=$row['order']?->items?->firstWhere('product_variant_id',$item->product_variant_id)) @php($weight=$orderItem?$orderItem->displayValueForStage($row['order']->status):$variantWeight($variant,$item->quantity)) @php($price=(float)($orderItem?->price??$item->unit_cost)) @php($amount=$orderItem?$orderItem->lineTotalForStage($row['order']->status):$item->quantity*$item->unit_cost)<tr><td>{{ $row['order']?->customer?->name??'Xuất hàng' }}<div class="report-note">{{ $row['order']?->code??$row['document']->document_number }}</div></td><td>{{ $variant?->product?->name??'Sản phẩm' }}</td><td>{{ $size($variant) }}</td><td class="num">{{ $number($item->quantity) }}</td><td class="num">{{ $number($weight,3) }} kg</td><td class="num">{{ $number($price) }}đ</td><td class="num money">{{ $number($amount) }}đ</td></tr>@endforeach @empty<tr><td colspan="7" class="empty">Không có hàng hoặc đơn xuất đi.</td></tr>@endforelse
</tbody><tfoot><tr class="total-row"><th colspan="6">TỔNG CỘNG</th><th class="num">{{ $number($outgoingTotal) }}đ</th></tr></tfoot></table></div></section>

<section class="daily-panel"><div class="daily-title"><h2>4. Hàng điều chuyển tới</h2><span class="badge bg-info text-dark">{{ $number($inventoryTransfers->sum(fn($transfer)=>$transfer->items->sum('quantity'))) }} sản phẩm</span></div><div class="table-responsive"><table class="table daily-table"><thead><tr><th>Sản phẩm</th><th>Size</th><th class="num">SL</th><th class="num">KL</th><th class="num">Giá</th><th class="num">Thành tiền</th></tr></thead><tbody>
@forelse($inventoryTransfers as $transfer) @foreach($transfer->items as $item) @php($variant=$item->variant)<tr><td>{{ $variant?->product?->name??'Sản phẩm' }}<div class="report-note">Từ {{ $transfer->sourceWarehouse?->name??'kho gửi' }}</div></td><td>{{ $size($variant) }}</td><td class="num">{{ $number($item->quantity) }}</td><td class="num">{{ $number($item->weight_kg,3) }} kg</td><td class="num">{{ $number($item->unit_cost) }}đ</td><td class="num money">{{ $number($item->quantity*$item->unit_cost) }}đ</td></tr>@endforeach @empty<tr><td colspan="6" class="empty">Không có hàng điều chuyển tới.</td></tr>@endforelse
</tbody><tfoot><tr class="total-row"><th colspan="5">TỔNG CỘNG</th><th class="num">{{ $number($inventoryTransferTotal) }}đ</th></tr></tfoot></table></div></section>

<section class="daily-panel"><div class="daily-title"><h2>5. Đơn điều chuyển tới</h2><span class="badge bg-warning text-dark">{{ $number($orderTransfers->sum(fn($transfer)=>$transfer->order?->items?->sum('quantity')??0)) }} sản phẩm</span></div><div class="table-responsive"><table class="table daily-table"><thead><tr><th>Khách hàng</th><th>Sản phẩm</th><th>Size</th><th class="num">SL</th><th class="num">KL</th><th class="num">Giá</th><th class="num">Thành tiền</th></tr></thead><tbody>
@forelse($orderTransfers as $transfer) @foreach($transfer->order?->items??[] as $item) @php($variant=$item->variant) @php($weight=$item->displayValueForStage($transfer->order->status))<tr><td>{{ $transfer->order?->customer?->name??'—' }}<div class="report-note">{{ $transfer->order?->code }} · Từ {{ $transfer->sourceWarehouse?->name??'kho gửi' }}</div></td><td>{{ $item->display_name }}</td><td>{{ $size($variant) }}</td><td class="num">{{ $number($item->quantity) }}</td><td class="num">{{ $number($weight,3) }} kg</td><td class="num">{{ $number($item->price) }}đ</td><td class="num money">{{ $number($item->lineTotalForStage($transfer->order->status)) }}đ</td></tr>@endforeach @empty<tr><td colspan="7" class="empty">Không có đơn điều chuyển tới.</td></tr>@endforelse
</tbody><tfoot><tr class="total-row"><th colspan="6">TỔNG CỘNG</th><th class="num">{{ $number($orderTransferTotal) }}đ</th></tr></tfoot></table></div></section>
@endsection
