@extends('layouts.warehouse')
@section('title', 'Báo cáo kho theo ngày')
@section('content')
<style>
.daily-head{background:linear-gradient(135deg,#0f766e,#164e63);color:#fff;border-radius:15px;padding:20px;margin-bottom:16px}.daily-panel{background:#fff;border:1px solid #e5ebf1;border-radius:13px;box-shadow:0 2px 9px rgba(15,23,42,.04);overflow:hidden;margin-bottom:16px}.daily-title{display:flex;justify-content:space-between;align-items:center;padding:13px 15px;border-bottom:1px solid #e8edf2}.daily-title h2{font-size:1rem;font-weight:750;margin:0}.daily-table{margin:0}.daily-table th{background:#f8fafc;color:#475569;font-size:.74rem;text-transform:uppercase;white-space:nowrap}.daily-table td,.daily-table th{padding:9px 11px;vertical-align:middle;border-color:#edf1f5}.empty{text-align:center;color:#64748b;padding:25px!important}.inventory-panel{position:sticky;top:78px;max-height:calc(100vh - 95px);overflow:auto}.total-row th{background:#dff4ec;color:#075e54;font-size:.9rem}.qty{white-space:nowrap;text-align:right;font-weight:700}
</style>
<div class="daily-head"><h1 class="h4 fw-bold mb-1">Một ngày làm việc — {{ $warehouse?->name ?? 'Toàn hệ thống' }}</h1><div class="opacity-75">{{ $from->format('d/m/Y') }}</div></div>
<div class="daily-panel p-3"><form method="GET" class="d-flex flex-wrap align-items-end gap-2"><div><label class="form-label fw-semibold">Ngày làm việc</label><input type="date" name="selected_date" class="form-control" value="{{ $selectedDate }}"></div><button class="btn btn-primary"><i class="bi bi-funnel me-1"></i>Xem</button></form></div>
<div class="row g-3 align-items-start"><div class="col-12 col-xl-7">
<section class="daily-panel"><div class="daily-title"><h2>1. Hàng điều chuyển tới</h2><span class="badge bg-info text-dark">{{ number_format($totals['transfer_quantity']) }} con</span></div><div class="table-responsive"><table class="table daily-table"><thead><tr><th>Đơn</th><th>Sản phẩm</th><th>Size</th><th class="qty">Số lượng</th></tr></thead><tbody>
@foreach($inventoryTransfers as $transfer) @foreach($transfer->items as $item)<tr><td>{{ $transfer->order?->customer?->name ?? 'Hàng điều chuyển' }}</td><td>{{ $item->variant?->product?->name ?? 'Sản phẩm' }}</td><td>{{ $item->variant?->size ?? '—' }}</td><td class="qty">{{ number_format($item->quantity) }}</td></tr>@endforeach @endforeach
@foreach($orderTransfers as $transfer) @php($items=$transfer->importDocument?->items??collect()) @if($items->isNotEmpty()) @foreach($items as $item)<tr><td>{{ $transfer->order?->customer?->name ?? 'Đơn điều chuyển' }}</td><td>{{ $item->productVariant?->product?->name ?? 'Sản phẩm' }}</td><td>{{ $item->productVariant?->size ?? '—' }}</td><td class="qty">{{ number_format($item->quantity) }}</td></tr>@endforeach @else @foreach($transfer->order?->items??[] as $item)<tr><td>{{ $transfer->order?->customer?->name ?? 'Đơn điều chuyển' }}</td><td>{{ $item->variant?->product?->name ?? 'Sản phẩm' }}</td><td>{{ $item->variant?->size ?? '—' }}</td><td class="qty">{{ number_format($item->quantity) }}</td></tr>@endforeach @endif @endforeach
@if($inventoryTransfers->isEmpty()&&$orderTransfers->isEmpty())<tr><td colspan="4" class="empty">Không có hàng điều chuyển tới.</td></tr>@endif</tbody></table></div></section>
<section class="daily-panel"><div class="daily-title"><h2>2. Hàng Thu mua DT3</h2><span class="badge bg-primary">{{ number_format($totals['supplier_quantity']) }} con</span></div><div class="table-responsive"><table class="table daily-table"><thead><tr><th>Sản phẩm</th><th>Size</th><th class="qty">Số lượng</th></tr></thead><tbody>
@forelse($supplierImports as $document) @foreach($document->items as $item)<tr><td>{{ $item->productVariant?->product?->name ?? 'Sản phẩm' }}</td><td>{{ $item->productVariant?->size ?? '—' }}</td><td class="qty">{{ number_format($item->quantity) }}</td></tr>@endforeach @empty<tr><td colspan="3" class="empty">Không có hàng thu mua DT3.</td></tr>@endforelse</tbody></table></div></section>
<section class="daily-panel"><div class="daily-title"><h2>3. Hàng &amp; đơn xuất đi</h2><span class="badge bg-danger">{{ number_format($exportedOrders->sum(fn($row) => $row['document']->items->sum('quantity'))) }} con</span></div><div class="table-responsive"><table class="table daily-table"><thead><tr><th>Đơn</th><th>Sản phẩm</th><th>Size</th><th class="qty">Số lượng</th></tr></thead><tbody>
@forelse($exportedOrders as $row) @foreach($row['document']->items as $item)<tr><td>{{ $row['order']?->customer?->name ?? 'Xuất hàng' }}</td><td>{{ $item->productVariant?->product?->name ?? 'Sản phẩm' }}</td><td>{{ $item->productVariant?->size ?? '—' }}</td><td class="qty">{{ number_format($item->quantity) }}</td></tr>@endforeach @empty<tr><td colspan="4" class="empty">Không có hàng hoặc đơn xuất đi.</td></tr>@endforelse</tbody></table></div></section>
</div><div class="col-12 col-xl-5"><section class="daily-panel inventory-panel"><div class="daily-title"><h2>Tồn kho cuối ngày</h2><span class="badge bg-success">{{ number_format($inventorySummary['totals']['closing']) }} con</span></div><div class="table-responsive"><table class="table daily-table"><thead><tr><th>Sản phẩm</th><th>Size</th><th class="qty">Tổng</th></tr></thead><tbody>
@php($visibleInventoryRows=0)
@foreach($inventorySummary['rows'] as $product) @foreach($product['variants'] as $variant) @if($variant['closing'] != 0) @php($visibleInventoryRows++)<tr><td>{{ $product['name'] }}</td><td>{{ $variant['size'] > 0 ? rtrim(rtrim(number_format($variant['size'],3,',','.'),'0'),',') : '—' }}</td><td class="qty">{{ number_format($variant['closing']) }}</td></tr>@endif @endforeach @endforeach
@if($visibleInventoryRows===0)<tr><td colspan="3" class="empty">Kho không có tồn cuối ngày.</td></tr>@endif
</tbody><tfoot><tr class="total-row"><th colspan="2">TỔNG TỒN NGÀY {{ $from->format('d/m/Y') }}</th><th class="qty">{{ number_format($inventorySummary['totals']['closing']) }} con</th></tr></tfoot></table></div></section></div></div>
@endsection
