<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Thu mua – @yield('title')</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"><style>
:root{--pc:#92400e;--pc2:#78350f;--accent:#fbbf24}body{background:#fffaf0;font-family:Inter,system-ui,sans-serif}.pc-side{position:fixed;inset:0 auto 0 0;width:250px;background:var(--pc);color:#fff;display:flex;flex-direction:column;z-index:100}.pc-brand{padding:1.1rem 1.25rem;background:var(--pc2);font-weight:800}.pc-nav-title{padding:.9rem 1.2rem .3rem;color:#fde68a;font-size:.72rem;text-transform:uppercase}.pc-link{display:flex;gap:.65rem;align-items:center;padding:.65rem 1.2rem;color:#fffbeb;text-decoration:none;border-left:3px solid transparent}.pc-link:hover,.pc-link.active{background:#ffffff18;color:#fff;border-left-color:var(--accent)}.pc-main{margin-left:250px}.pc-head{position:sticky;top:0;background:#fff;border-bottom:1px solid #fde7c0;padding:.8rem 1.3rem;z-index:50}.pc-content{padding:1.25rem}.card{border-radius:14px}.btn-primary{background:var(--pc);border-color:var(--pc)}@media(max-width:768px){.pc-side{transform:translateX(-100%)}.pc-main{margin-left:0}.pc-content{padding:.8rem}}
</style>@stack('styles')</head><body>@include('layouts.notifications')<aside class="pc-side"><div class="pc-brand"><i class="bi bi-basket2-fill me-2"></i>QUẢN LÝ THU MUA</div><nav class="overflow-auto flex-grow-1"><div class="pc-nav-title">Điều hành</div>
<a class="pc-link {{ request()->routeIs('procurement.dashboard')?'active':'' }}" href="{{ route('procurement.dashboard') }}"><i class="bi bi-speedometer2"></i>Dashboard</a>
<a class="pc-link {{ request()->routeIs('procurement.purchases.*')?'active':'' }}" href="{{ route('procurement.purchases.index') }}"><i class="bi bi-journal-text"></i>Nhật ký thu mua</a>
<a class="pc-link {{ request()->routeIs('procurement.farms.*')?'active':'' }}" href="{{ route('procurement.farms.index') }}"><i class="bi bi-houses"></i>Danh sách trang trại</a>
<a class="pc-link {{ request()->routeIs('procurement.conversions.*')?'active':'' }}" href="{{ route('procurement.conversions.index') }}"><i class="bi bi-diagram-3"></i>Quy đổi sơ chế</a>
<a class="pc-link {{ request()->routeIs('procurement.warehouse-shipments.*')?'active':'' }}" href="{{ route('procurement.warehouse-shipments.index') }}"><i class="bi bi-box-arrow-in-down"></i>Danh sách nhập kho</a>
<div class="pc-nav-title">Tài chính</div><a class="pc-link {{ request()->routeIs('procurement.finance-requests.*')?'active':'' }}" href="{{ route('procurement.finance-requests.index') }}"><i class="bi bi-file-earmark-text"></i>Phiếu yêu cầu</a></nav></aside>
<main class="pc-main"><header class="pc-head d-flex justify-content-between align-items-center gap-2"><div><strong>@yield('title','Dashboard')</strong><div class="small text-muted">@yield('subtitle')</div></div><div class="d-flex align-items-center gap-2">@include('layouts.partials.role_switcher')<span>{{ auth()->user()->name }}</span><form class="d-inline" method="POST" action="{{ route('logout') }}">@csrf<button class="btn btn-sm btn-outline-danger">Đăng xuất</button></form></div></header><section class="pc-content">@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if(isset($errors) && $errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif @yield('content')</section></main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>@include('layouts.partials.session_expiry_redirect')@stack('scripts')</body></html>
